# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC121(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.CSS_SELECTOR, ".user").click()
    self.driver.find_element(By.ID, "login").click()
    self.driver.find_element(By.ID, "login").send_keys("ADeCurtis123gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("Password123")
    self.driver.find_element(By.CSS_SELECTOR, ".fourth").click()
  
  def test_tC122(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.CSS_SELECTOR, ".user").click()
    self.driver.find_element(By.ID, "login").click()
    self.driver.find_element(By.ID, "login").send_keys("ADeCurtis123@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("Pass")
    self.driver.find_element(By.CSS_SELECTOR, ".fourth").click()
  
  def test_tC123(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.CSS_SELECTOR, ".user").click()
    self.driver.find_element(By.ID, "login").click()
    self.driver.find_element(By.ID, "login").send_keys("ADeCurtis123@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Password123")
    self.driver.find_element(By.CSS_SELECTOR, ".fourth").click()
  
